/* automatically generated from process-window-gtk3.ui */
#ifdef __SUNPRO_C
#pragma align 4 (process_window_ui)
#endif
#ifdef __GNUC__
static const char process_window_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char process_window_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.0\"/><object class=\"GtkWindow\" id=\"process-window\""
  "><property name=\"can_focus\">False</property><property name=\"title\" "
  "translatable=\"yes\">Task Manager</property><property name=\"default_wi"
  "dth\">490</property><property name=\"default_height\">465</property><pr"
  "operty name=\"icon_name\">utilities-system-monitor</property><child><ob"
  "ject class=\"GtkBox\" id=\"process-vbox\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"orientation\">vertical</property><child><object class=\"GtkToolbar\""
  " id=\"process-toolbar\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"show_arrow\">F"
  "alse</property><property name=\"icon_size\">1</property><child><object "
  "class=\"GtkToolButton\" id=\"toolbutton-about\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"stock_id\">gt"
  "k-about</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"homogeneous\">True</property></packing></child>"
  "<child><object class=\"GtkToolItem\" id=\"filter-toolitem\"><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"border_width\">2</property><child><object class=\"GtkAlignment\""
  " id=\"alignment1\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"xalign\">1</propert"
  "y><property name=\"xscale\">0.5</property><child><object class=\"GtkEnt"
  "ry\" id=\"filter-entry\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"invisible_char"
  "\">\342\200\242</property><property name=\"primary_icon_stock\">gtk-fin"
  "d</property><property name=\"secondary_icon_stock\">gtk-clear</property"
  "><property name=\"secondary_icon_sensitive\">False</property></object><"
  "/child></object></child></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"homogeneous\">False</property></packing></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkBox\" id=\"root-warning-"
  "box\"><property name=\"can_focus\">False</property><property name=\"ori"
  "entation\">vertical</property><child><object class=\"GtkEventBox\" id=\""
  "root-warning-ebox\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkLabel\" i"
  "d=\"root-warning-label\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"xpad\">6</pro"
  "perty><property name=\"ypad\">3</property><property name=\"label\" tran"
  "slatable=\"yes\">Warning, you are using the root account, you may harm "
  "your system.</property></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkSeparator\" id=\"root-warning-separator\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">1"
  "</property></packing></child><child><object class=\"GtkPaned\" id=\"mai"
  "nview-vpaned\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"orientation\">vertical</"
  "property><property name=\"position\">100</property><property name=\"pos"
  "ition_set\">True</property><child><object class=\"GtkBox\" id=\"graph-v"
  "box\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"orientation\">vertical</property"
  "><child><object class=\"GtkBox\" id=\"graph-hbox\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><chi"
  "ld><object class=\"GtkFrame\" id=\"graph-cpu\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"hexpand\">True</property><property name=\"vexpand\">False</pro"
  "perty><property name=\"border_width\">2</property><property name=\"labe"
  "l_xalign\">0</property><property name=\"shadow_type\">none</property><c"
  "hild><placeholder/></child><child type=\"label_item\"><placeholder/></c"
  "hild></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkFrame\" id=\"graph-mem\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"hexpand\">True</property><property name"
  "=\"vexpand\">False</property><property name=\"border_width\">2</propert"
  "y><property name=\"label_xalign\">0</property><property name=\"shadow_t"
  "ype\">none</property><child><placeholder/></child><child type=\"label_i"
  "tem\"><placeholder/></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">0</property></packing></child><child><placehol"
  "der/></child></object><packing><property name=\"resize\">False</propert"
  "y><property name=\"shrink\">False</property></packing></child><child><o"
  "bject class=\"GtkBox\" id=\"mainview-vbox\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindow\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><child><placeholder/></child></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child></object><pa"
  "cking><property name=\"resize\">True</property><property name=\"shrink\""
  ">True</property></packing></child></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">2</property></packing></child></object></child></obje"
  "ct></interface>"
};

static const unsigned process_window_ui_length = 6314u;

