/* automatically generated from settings-dialog-gtk3.ui */
#ifdef __SUNPRO_C
#pragma align 4 (settings_dialog_ui)
#endif
#ifdef __GNUC__
static const char settings_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char settings_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.0\"/><object class=\"GtkDialog\" id=\"settings-dialog\""
  "><property name=\"can_focus\">False</property><property name=\"border_w"
  "idth\">5</property><property name=\"title\" translatable=\"yes\">Settin"
  "gs for Task Manager</property><property name=\"resizable\">False</prope"
  "rty><property name=\"modal\">True</property><property name=\"destroy_wi"
  "th_parent\">True</property><property name=\"icon_name\">gtk-preferences"
  "</property><property name=\"type_hint\">normal</property><child interna"
  "l-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"orientation\">vertical</property><property name="
  "\"spacing\">2</property><child internal-child=\"action_area\"><object c"
  "lass=\"GtkButtonBox\" id=\"dialog-action_area\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"layout_style\">end</property><child><object class=\"GtkButton"
  "\" id=\"button-close\"><property name=\"label\">gtk-close</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">True</property><propert"
  "y name=\"use_stock\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">False<"
  "/property><property name=\"pack_type\">end</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkNoteb"
  "ook\" id=\"notebook\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"show_tabs\">False"
  "</property><child><object class=\"GtkBox\" id=\"hbox\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"border_width\">6</property><child><object class=\"GtkBo"
  "x\" id=\"vbox1\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"orientation\">vertica"
  "l</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkFrame\" id=\"frame-interface\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel_xalign\">0</property><property name=\"shadow_type\">none</property"
  "><child><object class=\"GtkAlignment\" id=\"alignment-interface\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"top_padding\">6</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox-i"
  "nterface\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "CheckButton\" id=\"button-show-application-icons\"><property name=\"lab"
  "el\" translatable=\"yes\">Show application icons</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">False</property><property name=\""
  "xalign\">0.5</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"button-ful"
  "l-command-line\"><property name=\"label\" translatable=\"yes\">Show ful"
  "l command lines</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">False</property><property name=\"xalign\">0.5</property><property"
  " name=\"draw_indicator\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkCheckButton\" id=\"button-more-precision\"><property name=\""
  "label\" translatable=\"yes\">Show values with more precision</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"xalign\">0.5</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "2</property></packing></child><child><object class=\"GtkCheckButton\" i"
  "d=\"button-process-tree\"><property name=\"label\" translatable=\"yes\""
  ">Show processes as tree</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"xalign\">0.5</property><"
  "property name=\"draw_indicator\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">4</property></packing></child><child>"
  "<object class=\"GtkCheckButton\" id=\"button-show-memory-in-xbytes\"><p"
  "roperty name=\"label\" translatable=\"yes\">Show memory usage in bytes<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"xalign\">0.5</property><property name=\"draw_ind"
  "icator\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">5</property></packing></child><child><object class=\"GtkBox\""
  " id=\"hbox-toolbar-style\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"spacing\">6"
  "</property><child><object class=\"GtkLabel\" id=\"label-toolbar-style\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Toolbar "
  "style:</property></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">False</property><property name=\"position"
  "\">0</property></packing></child><child><placeholder/></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">False</property><property name=\"position\">6</property></packing><"
  "/child></object></child></object></child><child type=\"label\"><object "
  "class=\"GtkLabel\" id=\"label-interface\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">&lt;b&gt;Interface style&lt;/b&gt;</pr"
  "operty><property name=\"use_markup\">True</property></object></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkFrame\" id=\"frame-misc\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment-misc\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"top_padding\">6</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkBox\" id=\"vbox-misc\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"orientatio"
  "n\">vertical</property><property name=\"spacing\">6</property><child><o"
  "bject class=\"GtkCheckButton\" id=\"button-prompt-terminate-task\"><pro"
  "perty name=\"label\" translatable=\"yes\">Prompt for terminating tasks<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"xalign\">0.5</property><property name=\"draw_ind"
  "icator\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkCheck"
  "Button\" id=\"button-show-status-icon\"><property name=\"label\" transl"
  "atable=\"yes\">Hide into the notification area</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">False</property><property name=\"x"
  "align\">0.5</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">1</property></"
  "packing></child></object></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label-misc\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">&lt;b&gt;Miscellaneous&lt;/b&gt;</p"
  "roperty><property name=\"use_markup\">True</property></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">1</property></p"
  "acking></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkSeparator\" id="
  "\"vseparator1\"><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"padding\">6</property><property name=\"position\">1</prop"
  "erty></packing></child><child><object class=\"GtkBox\" id=\"vbox2\"><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkFrame\" id=\"frame-information\"><property name=\"visible"
  "\">True</property><property name=\"sensitive\">False</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label_xalign\">0<"
  "/property><property name=\"shadow_type\">none</property><child><object "
  "class=\"GtkAlignment\" id=\"alignment-information\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"top_padding\">6</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkBox\" id=\"vbox-information\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"orientation\">vertical</property><prope"
  "rty name=\"spacing\">6</property><child><object class=\"GtkBox\" id=\"h"
  "box-refresh-rate\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"spacing\">6</proper"
  "ty><child><object class=\"GtkLabel\" id=\"label-refresh-rate\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">Refresh rate:</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkComboBox\" id=\"combob"
  "ox-refresh-rate\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">1</property></packing></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkLabel\" id=\"label-columns\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"xalign\">0</property><property name=\"label\" translatable="
  "\"yes\">Columns:</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">1</property></packing></child><child><object class=\"GtkAl"
  "ignment\" id=\"alignment-columns\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkScrolledWindow\" id="
  "\"scrolledwindow-columns\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"hscrollbar_p"
  "olicy\">never</property><property name=\"vscrollbar_policy\">never</pro"
  "perty><property name=\"shadow_type\">in</property><child><object class="
  "\"GtkTreeView\" id=\"treeview-columns\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><child internal-"
  "child=\"selection\"><object class=\"GtkTreeSelection\" id=\"treeview-se"
  "lection1\"/></child></object></child></object></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">2</property></packing></child></"
  "object></child></object></child><child type=\"label\"><object class=\"G"
  "tkLabel\" id=\"label-information\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">&lt;b&gt;Information&lt;/b&gt;</property><pro"
  "perty name=\"use_markup\">True</property></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"position\">0</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">2</property><"
  "/packing></child></object></child><child type=\"tab\"><object class=\"G"
  "tkLabel\" id=\"label\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">Settings</property></object><packing><property name=\"tab"
  "_fill\">False</property></packing></child><child><placeholder/></child>"
  "<child type=\"tab\"><placeholder/></child><child><placeholder/></child>"
  "<child type=\"tab\"><placeholder/></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object></chi"
  "ld><action-widgets><action-widget response=\"0\">button-close</action-w"
  "idget></action-widgets></object></interface>"
};

static const unsigned settings_dialog_ui_length = 13721u;

